shell = "zsh"

[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins]

# lazy load
[plugins.zsh-defer]
github = "romkatv/zsh-defer"
apply = ["source"]

[plugins.zsh-autocomplete]
github = "marlonrichert/zsh-autocomplete"
apply = ["defer"]

[plugins.ohmyzsh]
github = "ohmyzsh/ohmyzsh"
use = [
  "plugins/git/git.plugin.zsh",
  "plugins/sudo/sudo.plugin.zsh",
  "plugins/copypath/copypath.plugin.zsh",
  "plugins/copyfile/copyfile.plugin.zsh",
  "plugins/docker/docker.plugin.zsh",
  "plugins/docker-compose/docker-compose.plugin.zsh",
  "plugins/gh/gh.plugin.zsh"
]
apply = ["defer"]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]
