[tools]
"aqua:ogham/exa" = "0.10.1"
bat = "0.26.1"
bun = "1.3.9"
claude = "2.1.42"
delta = "0.18.2"
deno = "2.6.9"
fd = "10.3.0"
fzf = "0.67.0"
gh = "2.86.0"
ghq = "1.9.3"
lazygit = "0.59.0"
ni = "28.2.0"
node = "24.13.1"
opencode = "1.2.5"
pnpm = "10.29.3"
python = "3.14.3"
ripgrep = "15.1.0"
rust = "1.93.1"
starship = "1.24.2"
tmux = "3.6a"
uv = "0.10.2"
