[tools]
"aqua:micro-editor/micro" = "latest"
"aqua:ogham/exa" = "latest"
"aqua:rossmacarthur/sheldon" = "latest"
bat = "latest"
bun = "latest"
claude = "latest"
"conda:ffmpeg" = "latest"
delta = "latest"
deno = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
"github:steipete/gogcli" = "latest"
imagemagick = "latest"
jq = "latest"
lazygit = "latest"
ni = "latest"
node = "lts"
opencode = "latest"
pnpm = "latest"
python = "latest"
resvg = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
tmux = "latest"
uv = "latest"
yazi = { version = "latest", postinstall = "ya pkg install" }
zoxide = "latest"

[settings]
experimental = true
lockfile = true

[hooks]
postinstall = ""
