[tools]
bat = "0.26.1"
bun = "1.3.9"
claude = "2.1.42"
deno = "2.6.9"
gh = "2.86.0"
node = "24.13.1"
opencode = "1.2.5"
pnpm = "10.29.3"
python = "3.14.3"
rust = "1.93.1"
starship = "1.24.2"
uv = "0.10.2"
